# Generated by Django 5.0.7 on 2024-07-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dateofbirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.PositiveSmallIntegerField()),
                ('phone2', models.PositiveSmallIntegerField()),
                ('pan', models.CharField(max_length=10)),
                ('adhaar', models.CharField(max_length=12)),
                ('bank_account_type', models.CharField(choices=[('S', 'SAVING'), ('C', 'CURRENT')], max_length=1)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('bank_details', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='banks.bankdetails')),
            ],
        ),
    ]
