# Generated by Django 5.0.7 on 2024-07-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bank_account',
        ),
    ]
