# Generated by Django 5.0.7 on 2024-07-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_delete_address'),
        ('customer', '0004_remove_customer_bank_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
