# Generated by Django 5.0.7 on 2024-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ifsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.PositiveSmallIntegerField()),
                ('micr', models.PositiveSmallIntegerField()),
                ('bank', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=80)),
                ('centre', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=60)),
                ('contact', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
