# Generated by Django 5.0.7 on 2024-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifsc', '0002_alter_ifsc_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifsc',
            name='ifsc',
            field=models.CharField(max_length=11),
        ),
    ]
