# Generated by Django 5.0.7 on 2024-07-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
