# Generated by Django 5.0.7 on 2024-07-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
