# Generated by Django 5.0.7 on 2024-07-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bankaccount'),
        ('customer', '0004_remove_customer_bank_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
    ]
