# Generated by Django 5.0.7 on 2024-07-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0003_delete_bankaccount_delete_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('ifsc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=80)),
                ('centre', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('micr', models.CharField(max_length=9)),
            ],
        ),
    ]
