# Generated by Django 5.0.7 on 2024-07-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_bankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
