# Generated by Django 5.0.7 on 2024-07-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_delete_bankaccount'),
        ('customer', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=15)),
                ('account_type', models.CharField(choices=[('S', 'SAVING'), ('C', 'CURRENT')], max_length=1)),
                ('bank_details', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='banks.bankdetails')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
