# Generated by Django 5.0.7 on 2024-07-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_bankaccount'),
        ('customer', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
