# Generated by Django 5.0.7 on 2024-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
            ],
        ),
    ]
