# Generated by Django 5.0.7 on 2024-07-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pincodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PinCodes',
            new_name='Codes',
        ),
    ]
