# Generated by Django 5.0.7 on 2024-07-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pincodes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pincodes',
        ),
    ]
